// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsqqitnpevrrssnglwts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzcXFpdG5wZXZycnNzbmdsd3RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NjY0MzYsImV4cCI6MjA3MDE0MjQzNn0.8fI34VzRptezrmAJCCcbl7pHKkV8WddyMREOe5vkMCk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});